Class {
	#name : 'Porte2Entrees',
	#superclass : 'Porte',
	#instVars : [
		'entree1',
		'entree2'
	],
	#category : 'Projet_circuit',
	#package : 'Projet_circuit'
}

{ #category : 'accessing' }
Porte2Entrees >> entree1 [

	^ entree1
]

{ #category : 'accessing' }
Porte2Entrees >> entree1: anObject [

	entree1 := anObject
]

{ #category : 'accessing' }
Porte2Entrees >> entree2 [

	^ entree2
]

{ #category : 'accessing' }
Porte2Entrees >> entree2: anObject [

	entree2 := anObject
]
